### ISSUE TITLE
Standardized environment: Docker?

### ISSUE THREAD

**Issue by GJBoth** [nicolaseberle/flyTracker#4]
There's a script which builds an openCV environment. is it still up to date? Do you think it makes sense to move to docker instead of venvs? That could also help when going to GPU as we can use a cuda-enabled container...

**Comment by MichaelRera** [comment]
docker would make it easier to deploy in terms brainlessness and platform compatibility?

**Comment by GJBoth** [comment]
I'm of the opinion that it does, its basically a little OS you can deploy anywhere. So if we program for linux it doesnt matter if your run linux, Mac OS, windows. It's also easy to use a container with GPU support and just install openCV in it so we'd have GPU support. 

I can reuse a container from my own project so I hope to have a working example this weekend!
