### ISSUE TITLE
Proposed structure

### ISSUE THREAD

**Issue by GJBoth** [nicolaseberle/flyTracker#6]
Here's a quick proposed structure. We can refine it later and make it prettier (right now its ugly af), but it should capture the main idea:

video -> slice in time -> localize flies in each slice -> combine slices -> Link positions in each frame to unique identity (i.e. tracking) -> Slice arenas -> output

By slicing in time we're much more flexible w.r.t scaling and should be easier to go to gpu as well. We might be able get rid of some overhead by slicing the arenas only at the end as we don't have to load the whole video for each thread. Separating localization and tracking ensures modularity so that we can easily swap out algorithms...

**Comment by MichaelRera** [comment]
as discussed before, I agree regarding the increased flexibility but I wonder whether it is practical for resolving problematic occlusions.
nevertheless, it might be possible to tag those (based on particles' size?) and hence load only a stack close to this problem to be able to discriminate individual flies efficiently by gradient descent or other method requiring the time dimension

**Comment by GJBoth** [comment]
I came across this paper:

https://arxiv.org/pdf/1602.00763.pdf

The idea is pretty simple and in line with what I think you were already doing:
1. Detect flies using blob detector. Check if number of detected flies is equal to what we know.
2. Predict and filter fly location using kalman filter
3. Assign identities using Munkgres between detected bounding box and predicted bounding box.

Seems manageable,

**Comment by GJBoth** [comment]
Just summarizing our meeting below:
Pipeline:
1) Find ROI somehow (see below)
2) Blob detector for first layer
3) Each cluster gets a virtual number of flies using k-means
4) Match to previous frame using Hungarian, if flies are not matched we use 2 virtual flies etc...

@MichaelRera You figure out something with the arenas to make them easily detectable

Possible improvements:
1) Parallelize everything over time
2) Only do k-means once required
3) Distance matrix using scipy 
4) Move everything to GPU?
